services:
  db:
    image: postgres:14
    container_name: reparatur_db
    restart: always
    env_file:
      - .env
    volumes:
      - reparatur_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: reparatur_api
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    ports:
      - "8000:8000"
    command: >
      uvicorn api.main:app
      --host 0.0.0.0
      --port 8000
      --workers 4

volumes:
  reparatur_db_data:
